### PR TITLE
Plain java script with objects

### PR DESCRIPTION
**Pull request by Sboursen**
## Description

In this project, we built a basic website that allows users to add/remove books from a list. We used JavaScript objects and arrays to achieve that

### General requirements

- [x] There are no linter errors.
- [x] Followed the **Github flow**.
- [x] The documentation is professional.

### HTML/CSS/JS requirements

- [x] We followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [x] We followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- Implemented a basic UI with plain HTML.
- Created an array collection of objects that keeps a list of books.
- Created a function to add a new book to the collection, with title and author.
- Created a function to remove a book from the collection.
- Displayed all books saved in the collection in the top part of the page.
- Made sure that when a user clicks the "Add" button:
  - A new book is added to the collection.
  - The new book is displayed on the page.
- Made sure that when a user clicks the "Remove" button:
  - The correct book is removed from the collection.
  - The correct book disappears from the page.
- Made sure that data is preserved in the browser's memory by using [localStorage]
- Used only vanilla JavaScript.

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Review by ReshyResh — CHANGES_REQUESTED** [review]
# Hi team, 

### Good job so far on the project!
  - ✔ Well structured PR message.
  - ✔ Meaningful commit messages.
  - ✔ No linter errors.


#### There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [x] The remove function doesn't seem to be working all the time. Keep the local storage open in the window and follow these steps: 
  - Add 5 books, from 1 to 5, numbered.
  - Remove number 1 and number 2.
  - The view will look fine but the local storage will be wrong, and if the page gets refreshed the content changes.

I suggest you use the `filter()` method, but you can use any method that you prefer, as long as it works. Please make the delete function work properly and submit again.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sboursen** [comment]
Hi @ReshyResh 

Thank you for the review.
I'll take a look into it.

**Review by ReshyResh — APPROVED** [review]
# Hi team, 

### Good job addressing the changes requested requested previously.
#### Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by Sboursen** [comment]
@ReshyResh 
Thanks mate

**Pull request merged**
